### ISSUE TITLE
InventoryLists have NULL references

### ISSUE THREAD

**Issue by ghost** [Buckminsterfullerene02/UE-Modding-Tools#1]
Path - /Content/Character/InventoryLists

![image](https://github.com/Buckminsterfullerene02/UE-Modding-Tools/assets/104094945/770a4f6b-f0c0-4265-8253-3c5d40345817)

**Comment by Buckminsterfullerene02** [comment]
Wrong repo - please remake your issue in the [correct one](https://github.com/DRG-Modding/Community-Modkit).
