### ISSUE TITLE
Animation Sequence and Animation Montage have some problems

### ISSUE THREAD

**Issue by ghost** [Buckminsterfullerene02/UE-Modding-Tools#2]
I checked many animations for enemies and weapons, and it seems these have some problems. (But it's usable and easy to fix with manual editing)
But it might cause an issue when a modder want to make animation montage from an animation sequence and add sounds, animation notify etc, because animation sequence and montage have wrong values comparing from the base game. So the result won't be the same between the editor and in the game.

It seems many animation sequences have wrong framerate or playrate, it seems 2 times slower than usual. 

And montage's animation segmenet's end time has wrong value for the most of animation montages.
It looks all animation notifies are there, only EndTime has wrong value. 
![image](https://github.com/Buckminsterfullerene02/UE-Modding-Tools/assets/104094945/4483ddcd-039c-41fc-8b4a-67a8329e84f3)

**Comment by Buckminsterfullerene02** [comment]
Wrong repo - please remake your issue in the [correct one](https://github.com/DRG-Modding/Community-Modkit).
